server:
  port: 8080

bsm:
  client-id: ${BSM_CLIENT_ID}
  client-secret: ${BSM_CLIENT_SECRET}
  redirect-uri: http://127.0.0.1:8080/login/oauth2/code/bsm

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://dpg-d1p83qvfte5s73c2qebg-a:5432/muldum
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
  mvc:
    static-path-pattern: /uploads/**
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.debug: true
      mail.debug: true

logging:
  level:
    org.springframework.mail: DEBUG
    com.sun.mail.smtp: DEBUG

app:
  email:
    allowed-domain: "@bssm.hs.kr"
